title: Nutty.blog
description: "자유로운 개발 이야기"
logo_img: "/assets/img/nutty_icon.png"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: yoobinpark@gmail.com
github_username: yubeenpark
instagram_username: ooybeen
linkedin_username: yubeenPark0xx0


# External API
giscus_repo: "Yubeenpark/Yubeenpark.github.io"
giscus_repoId: "R_kgDOLlOA9Q"
giscus_category: "Comments"
giscus_categoryId: "DIC_kwDOLlOA9c4Cefl8"
goatcounter_code: nuttyCheck
google_analytics:

# # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                 #
#   Not recommended to touch the materials below  #
#                                                 #
#    Any changes may contribute to malfunction    #
#                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Build settings

# If you want to deploy Git Page, but choosing the second Installation method (described in README.md)
# rather than fork, then replace the below line with `remote_theme: byanko55/jekyll-theme-satellite`.
# Otherwise, DO NOT change it.
#theme: jekyll-theme-satellite
remote_theme: byanko55/jekyll-theme-satellite
exclude:
  - _posts

collections:
  pages:
    output: true
    permalink: /:path.html
    
plugins:
 -  jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"



# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
